ALTER TYPE "PetSpecies" ADD VALUE IF NOT EXISTS 'BIRD';
ALTER TYPE "PetSpecies" ADD VALUE IF NOT EXISTS 'REPTILE';
ALTER TYPE "PetSpecies" ADD VALUE IF NOT EXISTS 'SMALL_PET';
ALTER TYPE "PetSpecies" ADD VALUE IF NOT EXISTS 'AQUATIC';
ALTER TYPE "PetSpecies" ADD VALUE IF NOT EXISTS 'AMPHIBIAN';
ALTER TYPE "PetSpecies" ADD VALUE IF NOT EXISTS 'ARTHROPOD';
ALTER TYPE "PetSpecies" ADD VALUE IF NOT EXISTS 'SPECIAL_OTHER';

ALTER TABLE "Pet"
ADD COLUMN IF NOT EXISTS "weightKg" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "birthYear" INTEGER;
