-- AlterTable
ALTER TABLE "HospitalReview" ALTER COLUMN "hospitalName" DROP NOT NULL,
ALTER COLUMN "visitDate" DROP NOT NULL,
ALTER COLUMN "treatmentType" DROP NOT NULL,
ALTER COLUMN "rating" DROP NOT NULL;

-- AlterTable
ALTER TABLE "PlaceReview" ALTER COLUMN "placeName" DROP NOT NULL,
ALTER COLUMN "placeType" DROP NOT NULL,
ALTER COLUMN "isPetAllowed" DROP NOT NULL,
ALTER COLUMN "isPetAllowed" DROP DEFAULT,
ALTER COLUMN "rating" DROP NOT NULL;

-- AlterTable
ALTER TABLE "WalkRoute" ALTER COLUMN "routeName" DROP NOT NULL,
ALTER COLUMN "difficulty" DROP NOT NULL,
ALTER COLUMN "difficulty" DROP DEFAULT,
ALTER COLUMN "hasStreetLights" DROP NOT NULL,
ALTER COLUMN "hasStreetLights" DROP DEFAULT,
ALTER COLUMN "hasRestroom" DROP NOT NULL,
ALTER COLUMN "hasRestroom" DROP DEFAULT,
ALTER COLUMN "hasParkingLot" DROP NOT NULL,
ALTER COLUMN "hasParkingLot" DROP DEFAULT,
ALTER COLUMN "safetyTags" SET DEFAULT ARRAY[]::TEXT[];
